### get honlap
get http://localhost:3000/

### get my js
get http://localhost:3000/public/my.js


### get products
get http://localhost:3000/products/

### get product by id
get http://localhost:3000/products/apcj6tclbfhqung

### post product
post http://localhost:3000/products/
Content-Type: application/json

{
    "name": "Á7 <span onclick='x()'>Alma<script>function x(){alert('Betörtem XD')}</script></span>",
    "quantity": "66 <script>function x(){alert('Betörtem XD')}</script>",
    "price": 6500,
    "type": "fémáru"
}

### delete product by id
delete http://localhost:3000/products/1lvc06wcldbc5e2j


### put product by id
put http://localhost:3000/products/1lvc06wcldbc5e2j
Content-Type: application/json

{
    "name": "Á77",
    "quantity": 99,
    "price": 9500,
    "type": "fémáru9"
}

